import { AntoinePicture, BastienPicture, FrancoisPicture, MathewPicture } from "../../constants/images";

export  const teamMembers = [
    {
      id: "faq01",
      name: "Matthew Tharp",
      position: "Chief Executive Officer",
      email: "matt@hunter.io",
      linkedin: "https://www.linkedin.com/in/",
      twitter: "https://twitter.com/",
      countryFlag: "🇺🇸",
      imageSrc:MathewPicture,
      lat: "42.279167",
      long: "-71.416667",
    },
    {
      id: "faq02",
      name: "Antoine Finkelstein",
      position: "Co-founder",
      email: "antoine@hunter.io",
      linkedin: "https://www.linkedin.com/in/",
      twitter: "https://twitter.com/",
      countryFlag: "🇫🇷",
      imageSrc:AntoinePicture,
    lat: "46.227638",
      long: "2.213749",
    },
    {
      id: "faq03",
      name: "François Grante",
      position: "Co-founder",
      email: "francois@hunter.io",
      linkedin: "https://linkedin.com/in/fgrante",
      twitter: "https://twitter.com/fgrante",
      countryFlag: "🇯🇵",
      imageSrc:FrancoisPicture,
      lat: "36.204824",
      long: "138.252924",
    },
    {
      id: "faq04",
      name: "Bastien Libersa",
      position: "Head of engineering",
      email: "bastien@hunter.io",
      linkedin: "https://www.linkedin.com/in/",
      twitter: "https://twitter.com/",
      countryFlag: "🇫🇷",
      imageSrc:BastienPicture,
      lat: "46.227638",
      long: "2.213749",
    },
  ];